# Generated by Django 5.1.15 on 2026-09-07 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Bank or NBFC name', max_length=255)),
                ('product_types', models.JSONField(default=list, help_text="e.g. ['Unsecured Business Loan', 'Working Capital']")),
                ('min_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_vintage', models.DecimalField(decimal_places=1, default=0, help_text='Min years in business', max_digits=4)),
                ('eligibility_rules', models.JSONField(default=dict, help_text="Configurable JSON rules e.g. {'min_cibil': 680, 'gst_required': true, 'max_existing_emi_ratio': 0.5}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bankers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadBankerMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('selected', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='lenders.banker')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banker_matches', to='customers.lead')),
            ],
            options={
                'db_table': 'lead_banker_matches',
                'ordering': ['-match_score'],
            },
        ),
    ]
