# Generated by Django 5.1.15 on 2026-09-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asm',
            field=models.ForeignKey(blank=True, help_text='Assigned Reporting Manager / ASM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_telecallers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch or location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Unique Employee ID (e.g. ADMIN-001, ASM-001, TC-001)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Flag requiring password change on next login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='territory',
            field=models.CharField(blank=True, help_text='Territory coverage', max_length=100, null=True),
        ),
    ]
