# Generated by Django 5.1.15 on 2026-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_asm_user_branch_user_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credentials_email_status',
            field=models.CharField(choices=[('Credentials Sent', 'Credentials Sent'), ('Email Failed', 'Email Failed'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deletion flag to preserve historical records'),
        ),
    ]
