# Generated by Django 5.1.15 on 2026-09-07 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PAN Card', 'PAN Card'), ('Aadhaar Card', 'Aadhaar Card'), ('GST Certificate', 'GST Certificate'), ('Bank Statement', '12 Months Bank Statement'), ('ITR', '2 Years ITR with Computation'), ('Business Registration', 'Business Registration Proof'), ('Sanction Letter', 'Existing Loan Sanction Letter'), ('Other', 'Other Document')], max_length=60)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Uploaded', 'Uploaded'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
