# Generated by Django 5.1.15 on 2026-09-07 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('mobile_hash', models.CharField(db_index=True, max_length=64)),
                ('alt_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vintage', models.DecimalField(blank=True, decimal_places=1, help_text='Years in business', max_digits=4, null=True)),
                ('ownership_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_available', models.BooleanField(default=False)),
                ('itr_available', models.BooleanField(default=False)),
                ('banking_available', models.BooleanField(default=False)),
                ('monthly_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('existing_loans', models.BooleanField(default=False)),
                ('existing_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cibil_range', models.CharField(blank=True, max_length=50, null=True)),
                ('required_loan_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('loan_type', models.CharField(choices=[('Business Loan', 'Business Loan'), ('Working Capital', 'Working Capital'), ('Expansion', 'Expansion'), ('Machinery', 'Machinery'), ('Balance Transfer', 'Balance Transfer'), ('Debt Consolidation', 'Debt Consolidation'), ('Other', 'Other')], default='Business Loan', max_length=50)),
                ('lead_source', models.CharField(default='CSV Upload', max_length=100)),
                ('status', models.CharField(choices=[('New Lead', 'New Lead'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Eligibility Check', 'Eligibility Check'), ('Documents Pending', 'Documents Pending'), ('Login', 'Login'), ('Credit/PD', 'Credit/PD'), ('Approval', 'Approval'), ('Disbursement', 'Disbursement')], default='New Lead', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customer')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
