# Generated by Django 5.1.15 on 2026-09-07 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('outcome', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Call Later', 'Call Later'), ('Number Busy', 'Number Busy'), ('No Response', 'No Response'), ('Wrong Number', 'Wrong Number'), ('Already Taken Loan', 'Already Taken Loan'), ('Loan Required – Documents Pending', 'Loan Required – Documents Pending'), ('Eligible – Send Documents', 'Eligible – Send Documents'), ('Not Eligible', 'Not Eligible')], max_length=60)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('external_call_id', models.CharField(blank=True, help_text='Telephony provider call SID', max_length=100, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='customers.lead')),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calls',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.lead')),
            ],
            options={
                'db_table': 'follow_ups',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_url', models.URLField()),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBED', 'Transcribed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to='calls.call')),
            ],
            options={
                'db_table': 'voice_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
